list = ['id', 'name', '', '', 'email', 'website', 'fiscal position', 'pricelist', 'account receivable',
        'account payable', 'language', 'company code', 'company type', 'phone number', 'fax', 'tax number',
        'description', 'notes', 'tags', 'assignee', 'contact first name', 'contact last name', 'contact name',
        'contact phone number', 'contact email', 'contact position', 'contact fax', 'contact notes', 'contact mobile',
        'contact b2b ecommerce', 'address 1 label', 'address 1 company name', 'address 1 line 1', 'address 1 line 2',
        'address 1 suburb', 'address 1 city', 'address 1 state', 'address 1 country', 'address 1 zip code',
        'address 1 email', 'address 1 phone number', 'address 2 label', 'address 2 company name', 'address 2 line 1',
        'address 2 line 2', 'address 2 suburb', 'address 2 city', 'address 2 state', 'address 2 country',
        'address 2 zip code', 'address 2 email', 'address 2 phone number', 'address 3 label', 'address 3 company name',
        'address 3 line 1', 'address 3 line 2', 'address 3 suburb', 'address 3 city', 'address 3 state',
        'address 3 country', 'address 3 zip code', 'address 3 email', 'address 3 phone number', 'address 4 label',
        'address 4 company name', 'address 4 line 1', 'address 4 line 2', 'address 4 suburb', 'address 4 city',
        'address 4 state', 'address 4 country', 'address 4 zip code', 'address 4 email', 'address 4 phone number',
        'address 5 label', 'address 5 company name', 'address 5 line 1', 'address 5 line 2', 'address 5 suburb',
        'address 5 city', 'address 5 state', 'address 5 country', 'address 5 zip code', 'address 5 email',
        'address 5 phone number', 'address 6 label', 'address 6 company name', 'address 6 line 1', 'address 6 line 2',
        'address 6 suburb', 'address 6 city', 'address 6 state', 'address 6 country', 'address 6 zip code',
        'address 6 email', 'address 6 phone number', 'address 7 label', 'address 7 company name', 'address 7 line 1',
        'address 7 line 2', 'address 7 suburb', 'address 7 city', 'address 7 state', 'address 7 country',
        'address 7 zip code', 'address 7 email', 'address 7 phone number', 'address 8 label', 'address 8 company name',
        'address 8 line 1', 'address 8 line 2', 'address 8 suburb', 'address 8 city', 'address 8 state',
        'address 8 country', 'address 8 zip code', 'address 8 email', 'address 8 phone number', 'address 9 label',
        'address 9 company name', 'address 9 line 1', 'address 9 line 2', 'address 9 suburb', 'address 9 city',
        'address 9 state', 'address 9 country', 'address 9 zip code', 'address 9 email', 'address 9 phone number',
        'address 10 label', 'address 10 company name', 'address 10 line 1', 'address 10 line 2', 'address 10 suburb',
        'address 10 city', 'address 10 state', 'address 10 country', 'address 10 zip code', 'address 10 email',
        'address 10 phone number']
